[versions]
agp = "8.12.3"
androidxJunit = "1.1.5"
appcompatVersion = "1.6.1"
cardview = "1.0.0"
compiler = "4.16.0"
constraintlayoutVersion = "2.1.4"
converterGson = "3.0.0"
dexter = "6.2.3"
disklrucache = "2.0.2"
espressoCoreVersion = "3.5.1"
exoplayer = "2.19.1"
facebookAndroidSdk = "18.1.3"
glide = "5.0.5"
glideVersion = "4.16.0"
googleMaterial = "1.8.0"
googleServices = "4.4.3"
gradle = "8.12.3"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
loggingInterceptor = "5.1.0"
lottie = "6.1.0"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
annotation = "1.9.1"
lifecycleLivedataKtx = "2.9.4"
lifecycleViewmodelKtx = "2.9.4"
materialVersion = "1.10.0"
mockitoCore = "5.1.1"
navigationFragment = "2.9.5"
playServicesAuth = "21.4.0"
recyclerview = "1.3.2"
retrofit = "3.0.0"
roomCompiler = "2.8.1"
roomCompilerVersion = "2.8.3"
roomKtx = "2.8.3"
roomRuntime = "2.8.1"
roomRuntimeVersion = "2.6.1"
roomRxjava2 = "2.8.1"
roomTesting = "2.6.1"
rules = "1.5.0"
rxandroid = "2.1.1"
rxjava = "2.2.21"
securityCrypto = "1.1.0-alpha06"
swiperefreshlayout = "1.1.0"
viewpager2 = "1.0.0"
viewpager2Version = "1.1.0"
workRuntime = "2.9.0"
workRxjava2 = "2.9.0"
adapters = "3.2.0-alpha11"

[libraries]
adapter-rxjava2 = { module = "com.squareup.retrofit2:adapter-rxjava2", version.ref = "converterGson" }
appcompat-v161 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compiler" }
constraintlayout-v214 = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayoutVersion" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
dexter = { module = "com.karumi:dexter", version.ref = "dexter" }
disklrucache = { module = "com.jakewharton:disklrucache", version.ref = "disklrucache" }
espresso-core-v351 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
exoplayer = { module = "com.google.android.exoplayer:exoplayer", version.ref = "exoplayer" }
facebook-android-sdk = { module = "com.facebook.android:facebook-android-sdk", version.ref = "facebookAndroidSdk" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-v4160 = { module = "com.github.bumptech.glide:glide", version.ref = "glideVersion" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
junit-v115 = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycleLivedataKtx" }
lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycleLivedataKtx" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
material-v1100 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
material-v180 = { module = "com.google.android.material:material", version.ref = "googleMaterial" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "navigationFragment" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
room-compiler-v283 = { module = "androidx.room:room-compiler", version.ref = "roomCompilerVersion" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
room-runtime-v261 = { module = "androidx.room:room-runtime", version.ref = "roomRuntimeVersion" }
room-rxjava2 = { module = "androidx.room:room-rxjava2", version.ref = "roomRxjava2" }
room-testing = { module = "androidx.room:room-testing", version.ref = "roomTesting" }
rules = { module = "androidx.test:rules", version.ref = "rules" }
rxandroid = { module = "io.reactivex.rxjava2:rxandroid", version.ref = "rxandroid" }
rxjava = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxjava" }
security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }
swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
viewpager2-v110 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2Version" }
work-runtime = { module = "androidx.work:work-runtime", version.ref = "workRuntime" }
work-rxjava2 = { module = "androidx.work:work-rxjava2", version.ref = "workRxjava2" }
adapters = { group = "androidx.databinding", name = "adapters", version.ref = "adapters" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

